language: node_js
node_js:
  - "node"
install: npm install
script: npm run build && npm test
after_script:
- cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
notifications:
  email:
    on_success: never
    on_failure: always
