language: node_js
node_js:
  - "node"
install: npm install
script: npm run lint && npm run build && npm test
after_script:
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
notifications:
  email:
    on_success: never
    on_failure: always
deploy:
  skip_cleanup: true
  provider: npm
  email: mr.kovalenko.a.o@gmail.com
  on:
    branch: master
    tags: false
  tag: latest
  api_key: $NPM_TOKEN
